// CONFIG APP 
export const CHANGE_MENU_ACTIVE = 'CHANGE_MENU_ACTIVE'

// Authentication
export const AUTHENTICATE_USER_REQUEST = 'AUTHENTICATE_USER_REQUEST'
export const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS'
export const AUTHENTICATE_USER_FAILURE = 'AUTHENTICATE_USER_FAILURE'
export const AUTHENTICATE_USER_LOGOUT = 'AUTHENTICATE_USER_LOGOUT'

// Request
export const POST_DATA_REQUEST = 'POST_DATA_REQUEST'
export const POST_DATA_SUCCESS = 'POST_DATA_SUCCESS'
export const POST_DATA_FAILURE = 'POST_DATA_FAILURE'

// Address 
export const PROVINCE_REQUEST = 'PROVINCE_REQUEST'
export const PROVINCE_SUCCESS = 'PROVINCE_SUCCESS'
export const PROVINCE_FAILURE = 'PROVINCE_FAILURE'

export const CITY_REQUEST = 'CITY_REQUEST'
export const CITY_SUCCESS = 'CITY_SUCCESS'
export const CITY_FAILURE = 'CITY_FAILURE'

// Option for Book
export const CLASSIFICATION_REQUEST = 'CLASSIFICATION_REQUEST'
export const CLASSIFICATION_SUCCESS = 'CLASSIFICATION_SUCCESS'
export const CLASSIFICATION_FAILURE = 'CLASSIFICATION_FAILURE'

export const SUBJECT_REQUEST = 'SUBJECT_REQUEST'
export const SUBJECT_SUCCESS = 'SUBJECT_SUCCESS'
export const SUBJECT_FAILURE = 'SUBJECT_FAILURE'


